apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deepseek
  template:
    metadata:
      labels:
        app: deepseek
    spec:
      containers:
      - name: deepseek
        image: sirishap03/deepseek-app:latest
        ports:
        - containerPort: 8000
